/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'courseStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat, IDL.Nat)),
  'totalRegistrations' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'title' : IDL.Text,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'room' : IDL.Text,
  'isMandatory' : IDL.Bool,
  'category' : IDL.Text,
  'capacity' : IDL.Nat,
  'enrolledCount' : IDL.Nat,
});
export const Registration = IDL.Record({
  'id' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'courseIds' : IDL.Vec(IDL.Text),
  'employeeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getRegistrationsCsv' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminBypass' : IDL.Func([], [], []),
  'initializeCourses' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'resetAndGrantAdmin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfGrantAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'courseStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat, IDL.Nat)),
    'totalRegistrations' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'title' : IDL.Text,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'room' : IDL.Text,
    'isMandatory' : IDL.Bool,
    'category' : IDL.Text,
    'capacity' : IDL.Nat,
    'enrolledCount' : IDL.Nat,
  });
  const Registration = IDL.Record({
    'id' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'courseIds' : IDL.Vec(IDL.Text),
    'employeeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getRegistrationsCsv' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminBypass' : IDL.Func([], [], []),
    'initializeCourses' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'resetAndGrantAdmin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfGrantAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };