/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'courseStats' : Array<[string, string, bigint, bigint]>,
  'totalRegistrations' : bigint,
}
export interface Course {
  'id' : string,
  'startTime' : string,
  'title' : string,
  'endTime' : string,
  'date' : string,
  'room' : string,
  'isMandatory' : boolean,
  'category' : string,
  'capacity' : bigint,
  'enrolledCount' : bigint,
}
export interface Registration {
  'id' : string,
  'submittedAt' : bigint,
  'email' : string,
  'courseIds' : Array<string>,
  'employeeId' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'employeeId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimPreAuthorizedAdmin' : ActorMethod<[], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getRegistrations' : ActorMethod<[], Array<Registration>>,
  'getRegistrationsCsv' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminBypass' : ActorMethod<[], undefined>,
  'initializeCourses' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<
    [string, string, Array<string>],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'resetAndGrantAdmin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfGrantAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];